version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore SampleCore.csproj
      - dotnet tool install --global dotnet-sonarscanner --version 4.7.1
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output SampleCore.csproj
artifacts:
  files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml

<SonarQubeAnalysisProperties  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.sonarsource.com/msbuild/integration/2015/1">
<Property Name="sonar.host.url">http://ec2-13-233-250-92.ap-south-1.compute.amazonaws.com:9000/</Property>
<Property Name="sonar.login">admin</Property>
<Property Name="sonar.password">a69fa8df405a4606126c04ef943aa21ee9f13320
</Property>
</SonarQubeAnalysisProperties>
